### ISSUE TITLE
Overlapping packages

### ISSUE THREAD

**Issue by yrashk** [npgall/cqengine-stream-support#1]
I am trying to use StreamFactory  in my code but I get this exception:

```
Caused by: java.lang.ClassNotFoundException: com.googlecode.cqengine.query.StreamFactory not found by cqengine [90]
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1574)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_25]
    at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1415)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1595)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1525)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)[org.apache.felix.framework-5.4.0.jar:]
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_25]
    ... 38 more
```

I know it is a separate package, and therefore it is included into my features file:

``` xml
    <bundle>mvn:com.googlecode.cqengine/cqengine-stream-support/1.0.0</bundle>
```

And it shows up in the container:

```
> headers 91

CQEngine Stream Support (91)
----------------------------
Archiver-Version = Plexus Archiver
Bnd-LastModified = 1473813377955
Build-Jdk = 1.8.0_73
Built-By = npgall
Created-By = 1.8.0_73 (Oracle Corporation)
Manifest-Version = 1.0
Tool = Bnd-3.2.0.201605172007

Bundle-ManifestVersion = 2
Bundle-Name = CQEngine Stream Support
Bundle-SymbolicName = cqengine-stream-support
Bundle-Version = 1.0.0

Require-Capability =
    osgi.ee;filter:=(&(osgi.ee=JavaSE)(version=1.8))

Export-Package =
    com.googlecode.cqengine.query;version=1.0.0
```

And in my own bundle, the respective package is imported:

```
Import-Package =
        ...
    com.googlecode.cqengine.query;version="[1.0,2)",
```

What is interesting here is, if you look into the stack trace, it says it is the `cqengine` bundle that can't find this class.

Upon further investigation, I can see that both main bundle and this one define the same package of `com.googlecode.cqengine.query`.

Main:

```
   com.googlecode.cqengine.query;
        uses:="com.googlecode.cqengine,
            com.googlecode.cqengine.attribute,
            com.googlecode.cqengine.attribute.support,
            com.googlecode.cqengine.query.logical,
            com.googlecode.cqengine.query.option,
            com.googlecode.cqengine.query.simple";
        version=1.0.0,
```

This is a no go in OSGi. Packages can not overlap. My suggestion is to change a package for this library. Thoughts?

**Comment by npgall** [comment]
Hi Yurii,

Thanks for the detailed investigation!

I see how this is a problem. So I'll fix it in the next release - I'll move SteamFactory to a different package such as: com.googlecode.cqengine.stream

Thanks,
Niall

**Comment by yrashk** [comment]
thanks!
